sudo: false
language: bash

addons:
  apt:
    packages:
    - pandoc

deploy:
  # release builds
  provider: script
  script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -p 26753 -w 15636
  on:
    branch: /^v?\d+\.\d+\.\d+?$/
  # prerelease builds (don't push to wowi)
  provider: script
  script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -p 26753
  on:
    branch: /^v?\d+\.\d+(\.\d+)?(-\w+)?$/
