# this is derived from https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow
# the only real modifications I've made are to handle only specific tag formats
name: Package and build beta/alpha versions

# when a tag is created with the format vx.y.z-thing or x.y.z-thing
on:
  push:
    tags:
      - "*.*.*-*"
      - "v*.*.*-*"

# a workflow is built up as jobs, and within these jobs are steps
jobs:
  # "release" here can be anything in one word
  release:
    # we can run our steps on pretty much anything, but the "ubuntu-latest" image is a safe bet
    runs-on: ubuntu-latest

    # specify the environment variables used by the packager, matching the secrets from the project on GitHub
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # we first have to clone the AddOn project, which is simple enough, and is a required step
      - name: Clone project
        uses: actions/checkout@v2

      # package various release flavors
      - name: Package and release for Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic -p 26753 -w 23158 -a VBNBwg6x

      - name: Package and release for Burning Crusade Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc -p 26753 -w 23158 -a VBNBwg6x

      - name: Package and release
        uses: BigWigsMods/packager@master
        with:
          args: -p 26753 -w 23158 -a VBNBwg6x
